### ISSUE TITLE
Expose nWinTowers and nWonTowers to CPU players

### ISSUE THREAD

**Issue by maksverver** [ElTh0r0/stackandconquer#10]
As discussed on pull request #8: the CPU player should be able to know how many towers each player needs to complete to win, since this can affect its strategy. For example, trading a point for a point would be winning when you are 1 point ahead in a best-of-3, but it would be a losing move when you are 1 point behind.

The easiest solution is to expose both of these variables directly, but I would favor passing an array of number of towers *remaining* for each player, which is simpler because it involves one less variable, but it's also more flexible in that it supports asymmetric games, where one player needs more towers than the other, which might be useful as a handicap system (e.g., for practice, I might want to play a game where the AI needs 3 towers to win, but I only need 1).

Note that these representations are equivalent in that they can be converted. For example, the scenario where the AI needs 3 towers to win to my 1 can be modeled by setting nWinTowers to 3, and initializing nWonTowers to 0 for the AI and to 2 for me.

**Comment by maksverver** [comment]
This was actually fixed already in commit 5560869 (I missed a few commits).

**Comment by ElTh0r0** [comment]
> but I would favor passing an array of number of towers remaining for each player,

I like this! This is much more elegant than I implemented in 5560869 - I'll replace this with just one array containing the number of towers remaining to win.

Better don't put too much effort into updating your MinMax CPU at the moment until the updated interface is ready 😉.
