### ISSUE TITLE
Make board configuration available in `initCPU()`

### ISSUE THREAD

**Issue by maksverver** [ElTh0r0/stackandconquer#12]
It would be nice to have the initial empty board available in `initCPU()` already, possibly in the same format as `jsonBoard` passed to `callCPU()`, but without any player pieces.

This is not just a theoretic gripe. In my minimax player I actually have to defer the precalculation of possible moves to `callCPU()` just to be able to support custom boards, even though this information is constant throughout the game: https://github.com/maksverver/stackandconquer/blob/6d54a4e6e61830eda369de9619c9193d3cb2ae71/data/cpu/MinimaxCPU.js#L457-L472

**Comment by ElTh0r0** [comment]
I added the empty board to `initCPU`. So the main interface changes are done and I am exited to see new CPU scripts based on this 🙂
I tried to extend the [wiki page](https://github.com/ElTh0r0/stackandconquer/wiki/Create-CPU-opponent) accordingly
